port: 8000
environment: dev

token:
  expire: '4h'
  key: 'abc123'

database:
  name: 'properties'
  host: 'localhost'
  port: 27017
  # leave blank if no credentials
  username: ''
  password: ''
  srv: false
  options: